## Hello! This is a file with aditional data for the project.
## Its stored here so it can be easily imported to other files.
## Having it in the notebook would make it too long and messy - no-one likes to scroll through lines of just data. 
## Each set of data here will have an explanation of what it is, how it was obtained, and which notebook it was used in.

## Ship list
## This is a list of ships from the Wikipedia list found here -> https://en.wikipedia.org/wiki/Category:War_of_1812_ships_of_the_United_Kingdom
## The list is used in notebook x, where we automate the process of getting the data from the API. A for loop is created 
## that loops through this list, and calls the API for each ship.
## Note that, to keep the code manageable in the notebook, this list is restricted to ships with an HMS prefix, and only one word in the name.

ships = [
"Acasta",
"Aeolus",
"Aetna",
"Africa",
"Albion",
"Alceste",
"Anaconda",
"Asia",
"Avon",
"Ballahou",
"Bedford",
"Belle",
"Belvidera",
"Bold",
"Bonne",
"Borer",
"Boxer",
"Boyne",
"Bream",
"Bucephalus",
"Bulwark",
"Caledonia",
"Calliope",
"Carron",
"Centurion",
"Charybdis",
"Cherub",
"Childers",
"Chippeway",
"Colibri",
"Columbine",
"Confiance",
"Cornwallis",
"Cornwallis",
"Curlew",
"Cuttle",
"Cyane",
"Cydnus",
"Detroit",
"Detroit",
"Devastation",
"Diadem",
"Dictator",
"Diomede",
"Dominica",
"Dragon",
"Duke",
"Elephant",
"Endymion",
"Epervier",
"Erebus",
"Euryalus",
"Fairy",
"Fantome",
"Favourite",
"Forward",
"Fox",
"Frolic",
"Galatea",
"Garland",
"General",
"Goliath",
"Gorgon",
"Grecian",
"Guerriere",
"Havannah",
"Herald",
"Hermes",
"Herring",
"Horatio",
"Hydra",
"Java",
"La",
"Lady",
"Landrail",
"Laura",
"Leander",
"Leopard",
"Levant",
"Linnet",
"Little",
"Lord",
"Macedonian",
"Madagascar",
"Majestic",
"Manly",
"Marlborough",
"Medway",
"Menelaus",
"Moira",
"Moselle",
"Mosquidobit",
"Nemesis",
"Newcastle",
"Niemen",
"Norge",
"Nymphe",
"Orpheus",
"Pactolus",
"Pelican",
"Penguin",
"Peruvian",
"Phoebe",
"Pictou",
"Pictou",
"Pigmy",
"Plantagenet",
"Poictiers",
"Pomone",
"Prince",
"Princess",
"Psyche",
"Racoon",
"Ramillies",
"Recruit",
"Reindeer",
"Ringdove",
"Royal",
"Royal",
"Ruby",
"San",
"Sappho",
"Saturn",
"Sceptre",
"Seahorse",
"Severn",
"Shannon",
"Shelburne",
"Sir",
"Sophie",
"Southampton",
"Spartan",
"St",
"St",
"Starr",
"Statira",
"Success",
"Superb",
"Surprise",
"Terror",
"Thames",
"Thistle",
"Tonnant",
"Valiant",
"Vengeur",
"Victorious",
"Volcano",
"Whiting",
"Wolfe"
]

## Admiralty record series
## This list is used in notebook x, where we automate the process of getting the data from the API. 
## These series are series in the National Archives catalogue that represent sections of the Admiralty records. 
## They are formateed as sps.recordSeries=ADM%20xxx, where xxx is the number of the series. This is the format that the API uses.

admiralty_record_series = [
"sps.recordSeries=ADM%2050", # record_series_ADM_50
"sps.recordSeries=ADM%2051", # record_series_ADM_51
"sps.recordSeries=ADM%2052", # record_series_ADM_52
"sps.recordSeries=ADM%2053", # record_series_ADM_53
"sps.recordSeries=ADM%2054", # record_series_ADM_54
"sps.recordSeries=ADM%2055", # record_series_ADM_55
"sps.recordSeries=ADM%20101", # record_series_ADM_101
"sps.recordSeries=MT%2032" # record_series_MT_32
]